### ISSUE TITLE
The package “org.apache.log4j” does not exist. You might be missing a library.

### ISSUE THREAD

**Issue by AVHon** [TPMoyer/Grbl4P#1]
I've tried launching Grbl4P in Processing 3.5.4 and 4.0 beta 2, and the same problem occurs in both.

After manually installing the G4P and Game Control Plus libraries, there is still one dependency left, and running the sketch just notifies that the dependency is missing:

```
No library found for org.apache.log4j
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
The package “org.apache.log4j” does not exist. You might be missing a library.
```

Searching Processing's Contribution Manager for "log4j", "log", or "apache" doesn't turn up anything promising.

Platform: Debian 11 Stable "Bullseye", AMD64

**Comment by TPMoyer** [comment]
Updated my commit to have a \Processing\Libraries\   with the 2 libraries which are a bit less usual:    Jake Seigel's  log4j     and my fork of toxiclibs  (Had extended this 3D geometry library to allow doubles).

**Comment by TPMoyer** [comment]
Hey Alex:
      Sorry about that:    Updated my Grbl4P commit to include the two
processing libraries I use which are not on the processing standard list of
libraries:
I abandoned the Game Control Plus after discovering that it is not
compatible with the Raspberry Pi 32 bit ARM implementation.
Went to a relatively extreme solution of adding a second arduino with a USB
host hat, and connecting my logitech pro extreme 3D joystick off that.

First things first.   Please re-download from github, and move the
libraries to your processing correct location.   Believe on debian that
would be   $UserID\Sketchbook\Libraries\ directory
Do you intend to use a joystick off your AMD64 platform?

Would be interested in your feedback on the use experience and the GUI.
